# .github/workflows/release-electron-app.yml
# This workflow runs in your PRIVATE source code repository (dm-spark-test)
# but publishes releases to your PUBLIC release repository (dm-desktop-release)
# OR a separate DEV release repository (e.g., dm-desktop-dev-release).
# It also updates a separate configuration repository (dm-desktop-configs).

name: Build, Release, and Update Configs

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The git tag to build and release (e.g., v1.2.3 or dev-v0.1.0)."
        required: true
        type: string
      environment:
        description: "Select the build environment."
        required: true
        type: choice
        options:
          - development
          - production
        default: "development"
      backend_url:
        description: "Optional: Override backend URL. Leave blank for default."
        required: false
        type: string

jobs:
  release:
    runs-on: ${{ matrix.os }}

    # Conditionally select the GitHub Environment based on the manual input
    environment:
      name: ${{ github.event.inputs.environment }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Use the tag from the manual input
          ref: ${{ github.event.inputs.tag }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm ci

      # === MODIFIED STEP ===
      # This step now uses the `package:prod` script for all builds as requested.
      # The --publish flag tells electron-builder to create a release.
      - name: Build and Package Electron App
        run: npm run package:prod -- --publish onTag
        env:
          # GITHUB_TOKEN used by electron-builder. Sourced from the selected GitHub Environment.
          GITHUB_TOKEN: ${{ secrets.PAT_FOR_PUBLISH }}

          # Conditionally injects the PostHog API Key based on the environment input.
          VITE_POSTHOG_API_KEY: ${{ github.event.inputs.environment == 'production' && secrets.POSTHOG_PRD_API_KEY || secrets.POSTHOG_DEV_API_KEY }}

          # Injects the Backend URL. Uses the input if provided, otherwise defaults based on the environment.
          API_URL: ${{ github.event.inputs.backend_url || (github.event.inputs.environment == 'production' && 'https://dm-api.deepmodel.ai' || 'https://dm-api-cloud-run-sandbox-238037281416.us-central1.run.app') }}

          # Other secrets for code signing can be included here as before.

  # --- JOB TO UPDATE THE CONFIGURATION REPOSITORY ---
  update_config_repo:
    # This job runs only after the 'release' job has succeeded for all OSes.
    needs: release
    runs-on: ubuntu-latest

    # Use the same environment logic to access the PAT secret needed to push to the configs repo.
    environment:
      name: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout Configs Repository's Base Branch
        uses: actions/checkout@v4
        with:
          # Assumes the configs repo is in the same organization as this one.
          repository: ${{ github.repository_owner }}/dm-desktop-configs
          # Checks out the branch that contains the base config file.
          ref: "base_version"
          # Clones into a specific directory.
          path: "dm-desktop-configs"
          # Use the same PAT as the release job. It needs write permissions for the configs repo.
          token: ${{ secrets.PAT_FOR_CONFIGS }}

      - name: Create Version Branch and Update Files
        shell: bash
        run: |
          # 1. Determine the correct version name from the git tag input.
          TAG_NAME=${{ github.event.inputs.tag }}
          if [[ "$TAG_NAME" == dev-* ]]; then
            VERSION_NAME=${TAG_NAME#dev-}
          else
            VERSION_NAME=$TAG_NAME
          fi
          echo "Triggering Tag: $TAG_NAME"
          echo "Target Version & Branch Name: $VERSION_NAME"

          # 2. Navigate into the checked-out repository directory.
          cd dm-desktop-configs

          # 3. Create a new branch from the current HEAD (which is 'base_version').
          git checkout -b "$VERSION_NAME"

          # 4. Update the 'version' field in config.json using jq.
          jq --arg ver "$VERSION_NAME" '.version = $ver' config.json > config.json.tmp && mv config.json.tmp config.json
          echo "Updated config.json with version $VERSION_NAME:"
          cat config.json

          # 5. Create a new, empty changelog.md file.
          touch changelog.md
          echo "Created empty changelog.md"

          # 6. Configure git user for the commit.
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # 7. Add, commit, and push the new branch with the updated files.
          git add config.json changelog.md
          git commit -m "feat: Add config for version $VERSION_NAME"
          git push origin "$VERSION_NAME"
